/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BeneficiosTeaRouteImport } from './routes/beneficios-tea'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaContaIndexRouteImport } from './routes/minha-conta.index'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MinhaContaReservasRouteImport } from './routes/minha-conta.reservas'
import { Route as MinhaContaPerfilSensorialRouteImport } from './routes/minha-conta.perfil-sensorial'
import { Route as MinhaContaDadosRouteImport } from './routes/minha-conta.dados'
import { Route as EstabelecimentoSlugRouteImport } from './routes/estabelecimento.$slug'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo.$slug'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminEstabelecimentosIndexRouteImport } from './routes/admin.estabelecimentos.index'

const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosTeaRoute = BeneficiosTeaRouteImport.update({
  id: '/beneficios-tea',
  path: '/beneficios-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaIndexRoute = MinhaContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MinhaContaReservasRoute = MinhaContaReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaPerfilSensorialRoute =
  MinhaContaPerfilSensorialRouteImport.update({
    id: '/perfil-sensorial',
    path: '/perfil-sensorial',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaDadosRoute = MinhaContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => MinhaContaRoute,
} as any)
const EstabelecimentoSlugRoute = EstabelecimentoSlugRouteImport.update({
  id: '/estabelecimento/$slug',
  path: '/estabelecimento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/conteudo/$slug',
  path: '/conteudo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIndexRoute =
  AdminEstabelecimentosIndexRouteImport.update({
    id: '/estabelecimentos/',
    path: '/estabelecimentos/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin': typeof AdminIndexRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/minha-conta': typeof MinhaContaIndexRoute
  '/admin/estabelecimentos': typeof AdminEstabelecimentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/minha-conta'
    | '/admin/conteudo'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/reservas'
    | '/admin/'
    | '/conteudo/'
    | '/minha-conta/'
    | '/admin/estabelecimentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/admin/conteudo'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/reservas'
    | '/admin'
    | '/conteudo'
    | '/minha-conta'
    | '/admin/estabelecimentos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/minha-conta'
    | '/admin/conteudo'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/reservas'
    | '/admin/'
    | '/conteudo/'
    | '/minha-conta/'
    | '/admin/estabelecimentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiosTeaRoute: typeof BeneficiosTeaRoute
  CadastroRoute: typeof CadastroRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  ConteudoSlugRoute: typeof ConteudoSlugRoute
  EstabelecimentoSlugRoute: typeof EstabelecimentoSlugRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios-tea': {
      id: '/beneficios-tea'
      path: '/beneficios-tea'
      fullPath: '/beneficios-tea'
      preLoaderRoute: typeof BeneficiosTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/': {
      id: '/minha-conta/'
      path: '/'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof MinhaContaIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/minha-conta/reservas': {
      id: '/minha-conta/reservas'
      path: '/reservas'
      fullPath: '/minha-conta/reservas'
      preLoaderRoute: typeof MinhaContaReservasRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/perfil-sensorial': {
      id: '/minha-conta/perfil-sensorial'
      path: '/perfil-sensorial'
      fullPath: '/minha-conta/perfil-sensorial'
      preLoaderRoute: typeof MinhaContaPerfilSensorialRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/dados': {
      id: '/minha-conta/dados'
      path: '/dados'
      fullPath: '/minha-conta/dados'
      preLoaderRoute: typeof MinhaContaDadosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/estabelecimento/$slug': {
      id: '/estabelecimento/$slug'
      path: '/estabelecimento/$slug'
      fullPath: '/estabelecimento/$slug'
      preLoaderRoute: typeof EstabelecimentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/conteudo/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/': {
      id: '/admin/estabelecimentos/'
      path: '/estabelecimentos'
      fullPath: '/admin/estabelecimentos/'
      preLoaderRoute: typeof AdminEstabelecimentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEstabelecimentosIndexRoute: typeof AdminEstabelecimentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConteudoRoute: AdminConteudoRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEstabelecimentosIndexRoute: AdminEstabelecimentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaDadosRoute: typeof MinhaContaDadosRoute
  MinhaContaPerfilSensorialRoute: typeof MinhaContaPerfilSensorialRoute
  MinhaContaReservasRoute: typeof MinhaContaReservasRoute
  MinhaContaIndexRoute: typeof MinhaContaIndexRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaDadosRoute: MinhaContaDadosRoute,
  MinhaContaPerfilSensorialRoute: MinhaContaPerfilSensorialRoute,
  MinhaContaReservasRoute: MinhaContaReservasRoute,
  MinhaContaIndexRoute: MinhaContaIndexRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiosTeaRoute: BeneficiosTeaRoute,
  CadastroRoute: CadastroRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  ConteudoSlugRoute: ConteudoSlugRoute,
  EstabelecimentoSlugRoute: EstabelecimentoSlugRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
