/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreOsSelosRouteImport } from './routes/sobre-os-selos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ParaEstabelecimentosRouteImport } from './routes/para-estabelecimentos'
import { Route as MinhaContaRouteImport } from './routes/minha-conta'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BeneficiosTeaRouteImport } from './routes/beneficios-tea'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MinhaContaIndexRouteImport } from './routes/minha-conta.index'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as MinhaContaReservasRouteImport } from './routes/minha-conta.reservas'
import { Route as MinhaContaPerfisRouteImport } from './routes/minha-conta.perfis'
import { Route as MinhaContaPerfilSensorialRouteImport } from './routes/minha-conta.perfil-sensorial'
import { Route as MinhaContaDadosRouteImport } from './routes/minha-conta.dados'
import { Route as MinhaContaConfiguracoesRouteImport } from './routes/minha-conta.configuracoes'
import { Route as MinhaContaAvaliacoesRouteImport } from './routes/minha-conta.avaliacoes'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as EstabelecimentoSlugRouteImport } from './routes/estabelecimento.$slug'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo.$slug'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminEstabelecimentosIndexRouteImport } from './routes/admin.estabelecimentos.index'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as AdminEstabelecimentosIdRouteImport } from './routes/admin.estabelecimentos.$id'
import { Route as AdminConteudoAnalyticsRouteImport } from './routes/admin.conteudo.analytics'
import { Route as AdminConteudoIdRouteImport } from './routes/admin.conteudo.$id'
import { Route as AdminEstabelecimentosIdPreviewRouteImport } from './routes/admin.estabelecimentos.$id.preview'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreOsSelosRoute = SobreOsSelosRouteImport.update({
  id: '/sobre-os-selos',
  path: '/sobre-os-selos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEstabelecimentosRoute = ParaEstabelecimentosRouteImport.update({
  id: '/para-estabelecimentos',
  path: '/para-estabelecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaRoute = MinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosTeaRoute = BeneficiosTeaRouteImport.update({
  id: '/beneficios-tea',
  path: '/beneficios-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaContaIndexRoute = MinhaContaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MinhaContaRoute,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const MinhaContaReservasRoute = MinhaContaReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaPerfisRoute = MinhaContaPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaPerfilSensorialRoute =
  MinhaContaPerfilSensorialRouteImport.update({
    id: '/perfil-sensorial',
    path: '/perfil-sensorial',
    getParentRoute: () => MinhaContaRoute,
  } as any)
const MinhaContaDadosRoute = MinhaContaDadosRouteImport.update({
  id: '/dados',
  path: '/dados',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaConfiguracoesRoute = MinhaContaConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => MinhaContaRoute,
} as any)
const MinhaContaAvaliacoesRoute = MinhaContaAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => MinhaContaRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentoSlugRoute = EstabelecimentoSlugRouteImport.update({
  id: '/estabelecimento/$slug',
  path: '/estabelecimento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/conteudo/$slug',
  path: '/conteudo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIndexRoute =
  AdminEstabelecimentosIndexRouteImport.update({
    id: '/estabelecimentos/',
    path: '/estabelecimentos/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIdRoute = AdminEstabelecimentosIdRouteImport.update({
  id: '/estabelecimentos/$id',
  path: '/estabelecimentos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoAnalyticsRoute = AdminConteudoAnalyticsRouteImport.update({
  id: '/conteudo/analytics',
  path: '/conteudo/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoIdRoute = AdminConteudoIdRouteImport.update({
  id: '/conteudo/$id',
  path: '/conteudo/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIdPreviewRoute =
  AdminEstabelecimentosIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AdminEstabelecimentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/minha-conta/avaliacoes': typeof MinhaContaAvaliacoesRoute
  '/minha-conta/configuracoes': typeof MinhaContaConfiguracoesRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/perfis': typeof MinhaContaPerfisRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/minha-conta/avaliacoes': typeof MinhaContaAvaliacoesRoute
  '/minha-conta/configuracoes': typeof MinhaContaConfiguracoesRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/perfis': typeof MinhaContaPerfisRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin': typeof AdminIndexRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/minha-conta': typeof MinhaContaIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/admin/conteudo': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/explorar': typeof ExplorarRoute
  '/login': typeof LoginRoute
  '/minha-conta': typeof MinhaContaRouteWithChildren
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/minha-conta/avaliacoes': typeof MinhaContaAvaliacoesRoute
  '/minha-conta/configuracoes': typeof MinhaContaConfiguracoesRoute
  '/minha-conta/dados': typeof MinhaContaDadosRoute
  '/minha-conta/perfil-sensorial': typeof MinhaContaPerfilSensorialRoute
  '/minha-conta/perfis': typeof MinhaContaPerfisRoute
  '/minha-conta/reservas': typeof MinhaContaReservasRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/minha-conta/': typeof MinhaContaIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/minha-conta'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/minha-conta/avaliacoes'
    | '/minha-conta/configuracoes'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/perfis'
    | '/minha-conta/reservas'
    | '/admin/'
    | '/conteudo/'
    | '/minha-conta/'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/admin/conteudo/'
    | '/admin/estabelecimentos/'
    | '/admin/estabelecimentos/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/minha-conta/avaliacoes'
    | '/minha-conta/configuracoes'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/perfis'
    | '/minha-conta/reservas'
    | '/admin'
    | '/conteudo'
    | '/minha-conta'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/admin/conteudo'
    | '/admin/estabelecimentos'
    | '/admin/estabelecimentos/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/explorar'
    | '/login'
    | '/minha-conta'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/redefinir-senha'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/minha-conta/avaliacoes'
    | '/minha-conta/configuracoes'
    | '/minha-conta/dados'
    | '/minha-conta/perfil-sensorial'
    | '/minha-conta/perfis'
    | '/minha-conta/reservas'
    | '/admin/'
    | '/conteudo/'
    | '/minha-conta/'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/admin/conteudo/'
    | '/admin/estabelecimentos/'
    | '/admin/estabelecimentos/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiosTeaRoute: typeof BeneficiosTeaRoute
  CadastroRoute: typeof CadastroRoute
  ExplorarRoute: typeof ExplorarRoute
  LoginRoute: typeof LoginRoute
  MinhaContaRoute: typeof MinhaContaRouteWithChildren
  ParaEstabelecimentosRoute: typeof ParaEstabelecimentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SobreRoute: typeof SobreRoute
  SobreOsSelosRoute: typeof SobreOsSelosRoute
  TermosRoute: typeof TermosRoute
  ConteudoSlugRoute: typeof ConteudoSlugRoute
  EstabelecimentoSlugRoute: typeof EstabelecimentoSlugRoute
  LSlugRoute: typeof LSlugRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-os-selos': {
      id: '/sobre-os-selos'
      path: '/sobre-os-selos'
      fullPath: '/sobre-os-selos'
      preLoaderRoute: typeof SobreOsSelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-estabelecimentos': {
      id: '/para-estabelecimentos'
      path: '/para-estabelecimentos'
      fullPath: '/para-estabelecimentos'
      preLoaderRoute: typeof ParaEstabelecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta': {
      id: '/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof MinhaContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios-tea': {
      id: '/beneficios-tea'
      path: '/beneficios-tea'
      fullPath: '/beneficios-tea'
      preLoaderRoute: typeof BeneficiosTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-conta/': {
      id: '/minha-conta/'
      path: '/'
      fullPath: '/minha-conta/'
      preLoaderRoute: typeof MinhaContaIndexRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/minha-conta/reservas': {
      id: '/minha-conta/reservas'
      path: '/reservas'
      fullPath: '/minha-conta/reservas'
      preLoaderRoute: typeof MinhaContaReservasRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/perfis': {
      id: '/minha-conta/perfis'
      path: '/perfis'
      fullPath: '/minha-conta/perfis'
      preLoaderRoute: typeof MinhaContaPerfisRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/perfil-sensorial': {
      id: '/minha-conta/perfil-sensorial'
      path: '/perfil-sensorial'
      fullPath: '/minha-conta/perfil-sensorial'
      preLoaderRoute: typeof MinhaContaPerfilSensorialRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/dados': {
      id: '/minha-conta/dados'
      path: '/dados'
      fullPath: '/minha-conta/dados'
      preLoaderRoute: typeof MinhaContaDadosRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/configuracoes': {
      id: '/minha-conta/configuracoes'
      path: '/configuracoes'
      fullPath: '/minha-conta/configuracoes'
      preLoaderRoute: typeof MinhaContaConfiguracoesRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/minha-conta/avaliacoes': {
      id: '/minha-conta/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/minha-conta/avaliacoes'
      preLoaderRoute: typeof MinhaContaAvaliacoesRouteImport
      parentRoute: typeof MinhaContaRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimento/$slug': {
      id: '/estabelecimento/$slug'
      path: '/estabelecimento/$slug'
      fullPath: '/estabelecimento/$slug'
      preLoaderRoute: typeof EstabelecimentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/conteudo/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/': {
      id: '/admin/estabelecimentos/'
      path: '/estabelecimentos'
      fullPath: '/admin/estabelecimentos/'
      preLoaderRoute: typeof AdminEstabelecimentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/$id': {
      id: '/admin/estabelecimentos/$id'
      path: '/estabelecimentos/$id'
      fullPath: '/admin/estabelecimentos/$id'
      preLoaderRoute: typeof AdminEstabelecimentosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/analytics': {
      id: '/admin/conteudo/analytics'
      path: '/conteudo/analytics'
      fullPath: '/admin/conteudo/analytics'
      preLoaderRoute: typeof AdminConteudoAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$id': {
      id: '/admin/conteudo/$id'
      path: '/conteudo/$id'
      fullPath: '/admin/conteudo/$id'
      preLoaderRoute: typeof AdminConteudoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/$id/preview': {
      id: '/admin/estabelecimentos/$id/preview'
      path: '/preview'
      fullPath: '/admin/estabelecimentos/$id/preview'
      preLoaderRoute: typeof AdminEstabelecimentosIdPreviewRouteImport
      parentRoute: typeof AdminEstabelecimentosIdRoute
    }
  }
}

interface AdminEstabelecimentosIdRouteChildren {
  AdminEstabelecimentosIdPreviewRoute: typeof AdminEstabelecimentosIdPreviewRoute
}

const AdminEstabelecimentosIdRouteChildren: AdminEstabelecimentosIdRouteChildren =
  {
    AdminEstabelecimentosIdPreviewRoute: AdminEstabelecimentosIdPreviewRoute,
  }

const AdminEstabelecimentosIdRouteWithChildren =
  AdminEstabelecimentosIdRoute._addFileChildren(
    AdminEstabelecimentosIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConteudoIdRoute: typeof AdminConteudoIdRoute
  AdminConteudoAnalyticsRoute: typeof AdminConteudoAnalyticsRoute
  AdminEstabelecimentosIdRoute: typeof AdminEstabelecimentosIdRouteWithChildren
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
  AdminEstabelecimentosIndexRoute: typeof AdminEstabelecimentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConteudoIdRoute: AdminConteudoIdRoute,
  AdminConteudoAnalyticsRoute: AdminConteudoAnalyticsRoute,
  AdminEstabelecimentosIdRoute: AdminEstabelecimentosIdRouteWithChildren,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
  AdminEstabelecimentosIndexRoute: AdminEstabelecimentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MinhaContaRouteChildren {
  MinhaContaAvaliacoesRoute: typeof MinhaContaAvaliacoesRoute
  MinhaContaConfiguracoesRoute: typeof MinhaContaConfiguracoesRoute
  MinhaContaDadosRoute: typeof MinhaContaDadosRoute
  MinhaContaPerfilSensorialRoute: typeof MinhaContaPerfilSensorialRoute
  MinhaContaPerfisRoute: typeof MinhaContaPerfisRoute
  MinhaContaReservasRoute: typeof MinhaContaReservasRoute
  MinhaContaIndexRoute: typeof MinhaContaIndexRoute
}

const MinhaContaRouteChildren: MinhaContaRouteChildren = {
  MinhaContaAvaliacoesRoute: MinhaContaAvaliacoesRoute,
  MinhaContaConfiguracoesRoute: MinhaContaConfiguracoesRoute,
  MinhaContaDadosRoute: MinhaContaDadosRoute,
  MinhaContaPerfilSensorialRoute: MinhaContaPerfilSensorialRoute,
  MinhaContaPerfisRoute: MinhaContaPerfisRoute,
  MinhaContaReservasRoute: MinhaContaReservasRoute,
  MinhaContaIndexRoute: MinhaContaIndexRoute,
}

const MinhaContaRouteWithChildren = MinhaContaRoute._addFileChildren(
  MinhaContaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiosTeaRoute: BeneficiosTeaRoute,
  CadastroRoute: CadastroRoute,
  ExplorarRoute: ExplorarRoute,
  LoginRoute: LoginRoute,
  MinhaContaRoute: MinhaContaRouteWithChildren,
  ParaEstabelecimentosRoute: ParaEstabelecimentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SobreRoute: SobreRoute,
  SobreOsSelosRoute: SobreOsSelosRoute,
  TermosRoute: TermosRoute,
  ConteudoSlugRoute: ConteudoSlugRoute,
  EstabelecimentoSlugRoute: EstabelecimentoSlugRoute,
  LSlugRoute: LSlugRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
