/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SobreOsSelosRouteImport } from './routes/sobre-os-selos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ParaEstabelecimentosRouteImport } from './routes/para-estabelecimentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EstabelecimentosRouteImport } from './routes/estabelecimentos'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BeneficiosTeaRouteImport } from './routes/beneficios-tea'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as ConteudoIndexRouteImport } from './routes/conteudo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LSlugRouteImport } from './routes/l.$slug'
import { Route as EstabelecimentoSlugRouteImport } from './routes/estabelecimento.$slug'
import { Route as DemoMinhaContaRouteImport } from './routes/demo.minha-conta'
import { Route as DemoExplorarRouteImport } from './routes/demo.explorar'
import { Route as ConteudoSlugRouteImport } from './routes/conteudo.$slug'
import { Route as AdminReservasRouteImport } from './routes/admin.reservas'
import { Route as AdminAuditoriaRouteImport } from './routes/admin.auditoria'
import { Route as AdminEstabelecimentosIndexRouteImport } from './routes/admin.estabelecimentos.index'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as DemoEstabelecimentoSlugRouteImport } from './routes/demo.estabelecimento.$slug'
import { Route as AdminEstabelecimentosIdRouteImport } from './routes/admin.estabelecimentos.$id'
import { Route as AdminConteudoAnalyticsRouteImport } from './routes/admin.conteudo.analytics'
import { Route as AdminConteudoIdRouteImport } from './routes/admin.conteudo.$id'
import { Route as AdminEstabelecimentosIdPreviewRouteImport } from './routes/admin.estabelecimentos.$id.preview'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreOsSelosRoute = SobreOsSelosRouteImport.update({
  id: '/sobre-os-selos',
  path: '/sobre-os-selos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaEstabelecimentosRoute = ParaEstabelecimentosRouteImport.update({
  id: '/para-estabelecimentos',
  path: '/para-estabelecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentosRoute = EstabelecimentosRouteImport.update({
  id: '/estabelecimentos',
  path: '/estabelecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosTeaRoute = BeneficiosTeaRouteImport.update({
  id: '/beneficios-tea',
  path: '/beneficios-tea',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const ConteudoIndexRoute = ConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const LSlugRoute = LSlugRouteImport.update({
  id: '/l/$slug',
  path: '/l/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentoSlugRoute = EstabelecimentoSlugRouteImport.update({
  id: '/estabelecimento/$slug',
  path: '/estabelecimento/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMinhaContaRoute = DemoMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => DemoRoute,
} as any)
const DemoExplorarRoute = DemoExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => DemoRoute,
} as any)
const ConteudoSlugRoute = ConteudoSlugRouteImport.update({
  id: '/conteudo/$slug',
  path: '/conteudo/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservasRoute = AdminReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditoriaRoute = AdminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIndexRoute =
  AdminEstabelecimentosIndexRouteImport.update({
    id: '/estabelecimentos/',
    path: '/estabelecimentos/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const DemoEstabelecimentoSlugRoute = DemoEstabelecimentoSlugRouteImport.update({
  id: '/estabelecimento/$slug',
  path: '/estabelecimento/$slug',
  getParentRoute: () => DemoRoute,
} as any)
const AdminEstabelecimentosIdRoute = AdminEstabelecimentosIdRouteImport.update({
  id: '/estabelecimentos/$id',
  path: '/estabelecimentos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoAnalyticsRoute = AdminConteudoAnalyticsRouteImport.update({
  id: '/conteudo/analytics',
  path: '/conteudo/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoIdRoute = AdminConteudoIdRouteImport.update({
  id: '/conteudo/$id',
  path: '/conteudo/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEstabelecimentosIdPreviewRoute =
  AdminEstabelecimentosIdPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AdminEstabelecimentosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/demo': typeof DemoRouteWithChildren
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/explorar': typeof ExplorarRoute
  '/familias': typeof FamiliasRoute
  '/login': typeof LoginRoute
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/demo/explorar': typeof DemoExplorarRoute
  '/demo/minha-conta': typeof DemoMinhaContaRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/demo/estabelecimento/$slug': typeof DemoEstabelecimentoSlugRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/explorar': typeof ExplorarRoute
  '/familias': typeof FamiliasRoute
  '/login': typeof LoginRoute
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/demo/explorar': typeof DemoExplorarRoute
  '/demo/minha-conta': typeof DemoMinhaContaRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/admin': typeof AdminIndexRoute
  '/conteudo': typeof ConteudoIndexRoute
  '/demo': typeof DemoIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/demo/estabelecimento/$slug': typeof DemoEstabelecimentoSlugRoute
  '/admin/conteudo': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/beneficios-tea': typeof BeneficiosTeaRoute
  '/cadastro': typeof CadastroRoute
  '/demo': typeof DemoRouteWithChildren
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/explorar': typeof ExplorarRoute
  '/familias': typeof FamiliasRoute
  '/login': typeof LoginRoute
  '/para-estabelecimentos': typeof ParaEstabelecimentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sobre': typeof SobreRoute
  '/sobre-os-selos': typeof SobreOsSelosRoute
  '/termos': typeof TermosRoute
  '/admin/auditoria': typeof AdminAuditoriaRoute
  '/admin/reservas': typeof AdminReservasRoute
  '/conteudo/$slug': typeof ConteudoSlugRoute
  '/demo/explorar': typeof DemoExplorarRoute
  '/demo/minha-conta': typeof DemoMinhaContaRoute
  '/estabelecimento/$slug': typeof EstabelecimentoSlugRoute
  '/l/$slug': typeof LSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/conteudo/': typeof ConteudoIndexRoute
  '/demo/': typeof DemoIndexRoute
  '/admin/conteudo/$id': typeof AdminConteudoIdRoute
  '/admin/conteudo/analytics': typeof AdminConteudoAnalyticsRoute
  '/admin/estabelecimentos/$id': typeof AdminEstabelecimentosIdRouteWithChildren
  '/demo/estabelecimento/$slug': typeof DemoEstabelecimentoSlugRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/estabelecimentos/': typeof AdminEstabelecimentosIndexRoute
  '/admin/estabelecimentos/$id/preview': typeof AdminEstabelecimentosIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/demo'
    | '/estabelecimentos'
    | '/explorar'
    | '/familias'
    | '/login'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/demo/explorar'
    | '/demo/minha-conta'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/admin/'
    | '/conteudo/'
    | '/demo/'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/demo/estabelecimento/$slug'
    | '/admin/conteudo/'
    | '/admin/estabelecimentos/'
    | '/admin/estabelecimentos/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beneficios-tea'
    | '/cadastro'
    | '/estabelecimentos'
    | '/explorar'
    | '/familias'
    | '/login'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/demo/explorar'
    | '/demo/minha-conta'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/admin'
    | '/conteudo'
    | '/demo'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/demo/estabelecimento/$slug'
    | '/admin/conteudo'
    | '/admin/estabelecimentos'
    | '/admin/estabelecimentos/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/beneficios-tea'
    | '/cadastro'
    | '/demo'
    | '/estabelecimentos'
    | '/explorar'
    | '/familias'
    | '/login'
    | '/para-estabelecimentos'
    | '/privacidade'
    | '/sobre'
    | '/sobre-os-selos'
    | '/termos'
    | '/admin/auditoria'
    | '/admin/reservas'
    | '/conteudo/$slug'
    | '/demo/explorar'
    | '/demo/minha-conta'
    | '/estabelecimento/$slug'
    | '/l/$slug'
    | '/admin/'
    | '/conteudo/'
    | '/demo/'
    | '/admin/conteudo/$id'
    | '/admin/conteudo/analytics'
    | '/admin/estabelecimentos/$id'
    | '/demo/estabelecimento/$slug'
    | '/admin/conteudo/'
    | '/admin/estabelecimentos/'
    | '/admin/estabelecimentos/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeneficiosTeaRoute: typeof BeneficiosTeaRoute
  CadastroRoute: typeof CadastroRoute
  DemoRoute: typeof DemoRouteWithChildren
  EstabelecimentosRoute: typeof EstabelecimentosRoute
  ExplorarRoute: typeof ExplorarRoute
  FamiliasRoute: typeof FamiliasRoute
  LoginRoute: typeof LoginRoute
  ParaEstabelecimentosRoute: typeof ParaEstabelecimentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SobreRoute: typeof SobreRoute
  SobreOsSelosRoute: typeof SobreOsSelosRoute
  TermosRoute: typeof TermosRoute
  ConteudoSlugRoute: typeof ConteudoSlugRoute
  EstabelecimentoSlugRoute: typeof EstabelecimentoSlugRoute
  LSlugRoute: typeof LSlugRoute
  ConteudoIndexRoute: typeof ConteudoIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-os-selos': {
      id: '/sobre-os-selos'
      path: '/sobre-os-selos'
      fullPath: '/sobre-os-selos'
      preLoaderRoute: typeof SobreOsSelosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-estabelecimentos': {
      id: '/para-estabelecimentos'
      path: '/para-estabelecimentos'
      fullPath: '/para-estabelecimentos'
      preLoaderRoute: typeof ParaEstabelecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimentos': {
      id: '/estabelecimentos'
      path: '/estabelecimentos'
      fullPath: '/estabelecimentos'
      preLoaderRoute: typeof EstabelecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios-tea': {
      id: '/beneficios-tea'
      path: '/beneficios-tea'
      fullPath: '/beneficios-tea'
      preLoaderRoute: typeof BeneficiosTeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/conteudo/': {
      id: '/conteudo/'
      path: '/conteudo'
      fullPath: '/conteudo/'
      preLoaderRoute: typeof ConteudoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/l/$slug': {
      id: '/l/$slug'
      path: '/l/$slug'
      fullPath: '/l/$slug'
      preLoaderRoute: typeof LSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimento/$slug': {
      id: '/estabelecimento/$slug'
      path: '/estabelecimento/$slug'
      fullPath: '/estabelecimento/$slug'
      preLoaderRoute: typeof EstabelecimentoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/minha-conta': {
      id: '/demo/minha-conta'
      path: '/minha-conta'
      fullPath: '/demo/minha-conta'
      preLoaderRoute: typeof DemoMinhaContaRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/explorar': {
      id: '/demo/explorar'
      path: '/explorar'
      fullPath: '/demo/explorar'
      preLoaderRoute: typeof DemoExplorarRouteImport
      parentRoute: typeof DemoRoute
    }
    '/conteudo/$slug': {
      id: '/conteudo/$slug'
      path: '/conteudo/$slug'
      fullPath: '/conteudo/$slug'
      preLoaderRoute: typeof ConteudoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservas': {
      id: '/admin/reservas'
      path: '/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/auditoria': {
      id: '/admin/auditoria'
      path: '/auditoria'
      fullPath: '/admin/auditoria'
      preLoaderRoute: typeof AdminAuditoriaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/': {
      id: '/admin/estabelecimentos/'
      path: '/estabelecimentos'
      fullPath: '/admin/estabelecimentos/'
      preLoaderRoute: typeof AdminEstabelecimentosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/demo/estabelecimento/$slug': {
      id: '/demo/estabelecimento/$slug'
      path: '/estabelecimento/$slug'
      fullPath: '/demo/estabelecimento/$slug'
      preLoaderRoute: typeof DemoEstabelecimentoSlugRouteImport
      parentRoute: typeof DemoRoute
    }
    '/admin/estabelecimentos/$id': {
      id: '/admin/estabelecimentos/$id'
      path: '/estabelecimentos/$id'
      fullPath: '/admin/estabelecimentos/$id'
      preLoaderRoute: typeof AdminEstabelecimentosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/analytics': {
      id: '/admin/conteudo/analytics'
      path: '/conteudo/analytics'
      fullPath: '/admin/conteudo/analytics'
      preLoaderRoute: typeof AdminConteudoAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$id': {
      id: '/admin/conteudo/$id'
      path: '/conteudo/$id'
      fullPath: '/admin/conteudo/$id'
      preLoaderRoute: typeof AdminConteudoIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/estabelecimentos/$id/preview': {
      id: '/admin/estabelecimentos/$id/preview'
      path: '/preview'
      fullPath: '/admin/estabelecimentos/$id/preview'
      preLoaderRoute: typeof AdminEstabelecimentosIdPreviewRouteImport
      parentRoute: typeof AdminEstabelecimentosIdRoute
    }
  }
}

interface AdminEstabelecimentosIdRouteChildren {
  AdminEstabelecimentosIdPreviewRoute: typeof AdminEstabelecimentosIdPreviewRoute
}

const AdminEstabelecimentosIdRouteChildren: AdminEstabelecimentosIdRouteChildren =
  {
    AdminEstabelecimentosIdPreviewRoute: AdminEstabelecimentosIdPreviewRoute,
  }

const AdminEstabelecimentosIdRouteWithChildren =
  AdminEstabelecimentosIdRoute._addFileChildren(
    AdminEstabelecimentosIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminAuditoriaRoute: typeof AdminAuditoriaRoute
  AdminReservasRoute: typeof AdminReservasRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConteudoIdRoute: typeof AdminConteudoIdRoute
  AdminConteudoAnalyticsRoute: typeof AdminConteudoAnalyticsRoute
  AdminEstabelecimentosIdRoute: typeof AdminEstabelecimentosIdRouteWithChildren
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
  AdminEstabelecimentosIndexRoute: typeof AdminEstabelecimentosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditoriaRoute: AdminAuditoriaRoute,
  AdminReservasRoute: AdminReservasRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConteudoIdRoute: AdminConteudoIdRoute,
  AdminConteudoAnalyticsRoute: AdminConteudoAnalyticsRoute,
  AdminEstabelecimentosIdRoute: AdminEstabelecimentosIdRouteWithChildren,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
  AdminEstabelecimentosIndexRoute: AdminEstabelecimentosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DemoRouteChildren {
  DemoExplorarRoute: typeof DemoExplorarRoute
  DemoMinhaContaRoute: typeof DemoMinhaContaRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoEstabelecimentoSlugRoute: typeof DemoEstabelecimentoSlugRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoExplorarRoute: DemoExplorarRoute,
  DemoMinhaContaRoute: DemoMinhaContaRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoEstabelecimentoSlugRoute: DemoEstabelecimentoSlugRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeneficiosTeaRoute: BeneficiosTeaRoute,
  CadastroRoute: CadastroRoute,
  DemoRoute: DemoRouteWithChildren,
  EstabelecimentosRoute: EstabelecimentosRoute,
  ExplorarRoute: ExplorarRoute,
  FamiliasRoute: FamiliasRoute,
  LoginRoute: LoginRoute,
  ParaEstabelecimentosRoute: ParaEstabelecimentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SobreRoute: SobreRoute,
  SobreOsSelosRoute: SobreOsSelosRoute,
  TermosRoute: TermosRoute,
  ConteudoSlugRoute: ConteudoSlugRoute,
  EstabelecimentoSlugRoute: EstabelecimentoSlugRoute,
  LSlugRoute: LSlugRoute,
  ConteudoIndexRoute: ConteudoIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
